### PR TITLE
Update MAINTAINERS.MD

### PR DESCRIPTION
**Pull request by DanXu-ChinaTelecom**
Add Mr Yong Deng（China Telecom）and remove Mr Xianyang Zhang（China Telecom）

#### What type of PR is this?

Add one of the following kinds:
* subproject management

#### What this PR does / why we need it:

update maintainer

```

### CODE REVIEW

**Comment by DanXu-ChinaTelecom** [comment]
@zxyxwz Thanks for your work

**Comment by zxyxwz** [comment]
Due to a job adjustment, my work has been taken over by Mr. Deng Yong. He is an expert in this field. I'm sure he will better promote the definition of this API.

**Review by zxyxwz — APPROVED** [review]

**Comment by hdamker** [comment]
@zxyxwz Thanks also from my side. 
@ DENGYONG18 welcome - I have invited you to @camaraproject/number-verification_maintainers. Please check that you received the invitation from GitHub to the CAMARA organization and accept it.
If this is done we can merge the PR.

**Comment by DENGYONG18** [comment]
Hi, Herbert. It's Yong Deng from China Telecom. I've accepted the invatation and joined CAMARA. I will promote the definition of Verified Caller API. Please add me to this project and authorize me to upload documents and YAML file. Thank you!

**Comment by hdamker** [comment]
> Hi, Herbert. It's Yong Deng from China Telecom. I've accepted the invatation and joined CAMARA. I will promote the definition of Verified Caller API. Please add me to this project and authorize me to upload documents and YAML file. Thank you!

Hi Yong Deng, thanks for accepting the invitation, you are now in the Maintainer group of the repository. But there is no such thing like direct upload of documents and YAML files. We are following the "fork and pull" model, which means you have to create/change the files in your personal fork of the repository and then open a pull request which can be review by the community. It has to get one Codeowner approval and can be only merged by a Codeowner. For details see https://github.com/camaraproject/Governance/blob/main/CONTRIBUTING.md

**Review by hdamker — APPROVED** [review]

**Pull request merged**
